### PR TITLE
Allow config to blacklist packages from sort

### LINKED ISSUE #33: Ability to ignore certain packages in sort order
Are you opening a **BUG REPORT** or a **FEATURE REQUEST / CODE CHANGE**?

There is a section for each below.  Please complete the appropriate section and remove the other one.

We realize there is a lot of data requested here. We ask only that you do your best to provide as much information as possible so we can better help you.

# FEATURE REQUEST / CODE CHANGE

* [x] I have deleted the **BUG REPORT** section

## Summary
* [x] Provide a general summary of the requested feature in the title above
* [x] Provide a one-paragraph explanation of the requested feature:

It'd be nice to configure the `sort-import-declarations` rule to ignore certain packages while ensuring all other packages are still sorted properly. The primary use case for this is making sure a polyfill is imported before all of the packages that will depend on said polyfill being in place.

## Motivation
* Describe the big picture of your feature to communicate why it should be added.
  * Why are we doing this?
  * What use cases does it support?
  * What is the expected outcome?

## Detailed design
This is the bulk of the Feature Request / Code Change.

Explain the design in enough detail for somebody familiar with this repository to understand, and for somebody familiar with the implementation to implement. This should get into specifics and corner-cases, and include examples of how the feature is used. Any new terminology should be defined here.

## How we teach this

* What names and terminology work best for these concepts and why?
* How should this feature be introduced and taught to existing users?

## Drawbacks

* Why should we ***not*** do this? Please consider the impact...
  * ...on teaching this
  * ...on the integration of this feature with other existing and planned features
  * ...on the impact of the API churn on existing apps
  * ...etc.
* There are tradeoffs to choosing any path, please attempt to identify them here.

## Alternatives

* What other designs have been considered? What is the impact of not doing this?
* This section could also include prior art, that is, how other addons or libraries in the same domain have solved this problem.

## Unresolved questions

* Optional, but suggested for first drafts. What parts of the design are still TBD?

### PR DESCRIPTION
**Pull request by sandersky**
# Overview

## Does this PR close an existing issue?
Yes

## Summary
Provide a general summary of the issue addressed in the title above

## Issue Number(s)

* Closes #33

## Checklist
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] I have evaluated if the _README.md_ documentation needs to be updated
* [x] I have evaluated if DocBlock headers needed to be added or updated
* [x] I have verified that lint and tests pass locally with my changes
* [ ] If a fork of a dependent package had to be made to address the issue this PR closes:
  * [ ] I noted in the fork's _README.md_ the reason the fork was created
  * [ ] I have opened an upstream issue detailing what was deficient about the dependency
  * [ ] I have opened an upstream PR addressing this deficiency
  * [ ] I have opened an issue in this repository to track this PR and schedule the removal of the usage of the fork

# Semver

**This project uses [semver](http://semver.org), please check the scope of this PR:**

- [ ] #none#
- [ ] #patch#
- [x] #minor#
- [ ] #major#

# CHANGELOG

-  **Added** `ignore` configuration for `sort-import-declarations` to ignore certain packages such as polyfills.

### CODE REVIEW

**Comment by sandersky** [comment]
@cstolli @sophypal I'm not sure how quickly Ciena engineers look at open source contributions or who to ping if need be on PR's so I'm tagging you both.

**Comment by sophypal** [comment]
@sandersky Just throwing out some questions to better understand the requirements. Is it required to have polyfills at the top? I was confused because I thought import order doesn't matter.

**Comment by sandersky** [comment]
@sophypal imports are hoisted to the top in the transpiled code but if you have something like the following:
```js
import {fetchUsers} from 'awesome-api'
import 'fetch-polyfil'
```

`awesome-api` may operate on the assumption that `window.fetch` is defined as soon as it is loaded, which would happen before the polyfill loads. An example of how this might happen would be:

**awesome-api**
```js
const {fetch} = window

export const fetchUsers = fetch.bind(null, '/users')
```

**Comment by sophypal** [comment]
@sandersky Thanks. I guess we never run into that here because polyfills are loaded before Ember's loader comes into play but that ultimately depends on how its shimmed and imported. Seeing as how this plugin isnt specific to Ember and you originally wrote it, I'll approve.

**Review by sophypal — APPROVED** [review]

**Pull request merged**
